<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<Folder Include="Data\" />
	<Folder Include="Migrations\" />
	<Folder Include="Seeder\" />
	  
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PeakWise.Application\PeakWise.Application.csproj" />
    <ProjectReference Include="..\PeakWise.Domain\PeakWise.Domain.csproj" />
    <ProjectReference Include="..\PeakWise.Shared\PeakWise.Shared.csproj" />
  </ItemGroup>

</Project>
